apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prometheus-node-exporter
spec:
  selector:
    matchLabels:
      name: prometheus-node-exporter
  template:
    metadata:
      labels:
        name: prometheus-node-exporter
    spec:
      containers:
        - name: prometheus-node-exporter
          image: prom/node-exporter:latest
          ports:
            - containerPort: 9100
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-node-exporter
spec:
  selector:
    name: prometheus-node-exporter
  ports:
    - port: 9100        # The port exposed inside the cluster
      targetPort: 9100   # The container's port
      nodePort: 30007    # The external port on each node
  type: NodePort         # Expose the service on a node portkub 
